# Generated by Django 4.0.4 on 2022-08-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_product_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('mobile', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=225)),
                ('about', models.TextField()),
                ('image', models.ImageField(upload_to='image/')),
            ],
        ),
    ]
